from django.db import models

# Create your models here.

class Match(models.Model):
    FTHG = models.IntegerField()
    FTAG = models.IntegerField()
    FTR = models.IntegerField()
    HS = models.IntegerField()
    AS = models.IntegerField()
    Referee = models.IntegerField()

    HomeTeam_Arsenal	= models.BooleanField()
    HomeTeam_Aston_Villa	= models.BooleanField()
    HomeTeam_Bournemouth	= models.BooleanField()
    HomeTeam_Brentford	= models.BooleanField()
    HomeTeam_Brighton	= models.BooleanField()
    HomeTeam_Burnley	= models.BooleanField()
    HomeTeam_Chelsea	= models.BooleanField()
    HomeTeam_Crystal_Palace	= models.BooleanField()
    HomeTeam_Everton	= models.BooleanField()
    HomeTeam_Fulham	= models.BooleanField()
    HomeTeam_Liverpool	= models.BooleanField()
    HomeTeam_Luton	= models.BooleanField()
    HomeTeam_Man_City	= models.BooleanField()
    HomeTeam_Man_United	= models.BooleanField()
    HomeTeam_Newcastle	= models.BooleanField()
    HomeTeam_Nottingham_Forest	= models.BooleanField()
    HomeTeam_Sheffield_United	= models.BooleanField()
    HomeTeam_Tottenham	= models.BooleanField()
    HomeTeam_West_Ham	= models.BooleanField()
    HomeTeam_Wolves	= models.BooleanField()
    AwayTeam_Arsenal	= models.BooleanField()
    AwayTeam_Aston_Villa	= models.BooleanField()
    AwayTeam_Bournemouth	= models.BooleanField()
    AwayTeam_Brentford	= models.BooleanField()
    AwayTeam_Brighton	= models.BooleanField()
    AwayTeam_Burnley	= models.BooleanField()
    AwayTeam_Chelsea	= models.BooleanField()
    AwayTeam_Crystal_Palace	= models.BooleanField()
    AwayTeam_Everton	= models.BooleanField()
    AwayTeam_Fulham	= models.BooleanField()
    AwayTeam_Liverpool	= models.BooleanField()
    AwayTeam_Luton	= models.BooleanField()
    AwayTeam_Man_City	= models.BooleanField()
    AwayTeam_Man_United	= models.BooleanField()
    AwayTeam_Newcastle	= models.BooleanField()
    AwayTeam_Nottingham_Forest	= models.BooleanField()
    AwayTeam_Sheffield_United	= models.BooleanField()
    AwayTeam_Tottenham	= models.BooleanField()
    AwayTeam_West_Ham	= models.BooleanField()
    AwayTeam_Wolves= models.BooleanField()
